var logSettings=null,logEventURL="",creativeSalt=undefined;window.addEventListener('message',function(m){if(m.data.logSettings)logSettings=m.data.logSettings;if(m.data.trackingLinks)logEventURL=m.data.trackingLinks.e;if(m.data.salt)creativeSalt=m.data.salt;if(m.data.clickthru){window['clickthru']=m.data.clickthru;}});var QueryString=function(){var query_string={};var query=window.location.search.substring(1);var vars=query.split("&");for(var i=0;i<vars.length;i++){var pair=vars[i].split("=");if(typeof query_string[pair[0]]==="undefined")query_string[pair[0]]=pair[1];else if(typeof query_string[pair[0]]==="string")query_string[pair[0]]=pair[1];}
return query_string;}();if(typeof QueryString.clickthru!='undefined'){window['clickthru']=unescape(QueryString.clickthru);window['clicktag']=unescape(QueryString.clickthru);window['clickThrough']=unescape(QueryString.clickthru);window['clickTag']=unescape(QueryString.clickthru);window['clickTAG']=unescape(QueryString.clickthru);}
function getClickLink(tag){if(typeof QueryString[tag]!='undefined')return unescape(QueryString[tag]);else if(typeof window[tag]!='undefined')return window[tag];else if(typeof QueryString['clickthru']!='undeinfed')return unescape(QueryString['clickthru']);else if(typeof QueryString['clickTag']!='undeinfed')return unescape(QueryString['clickTag']);else if(typeof QueryString['clickTAG']!='undeinfed')return unescape(QueryString['clickTAG']);return '';}
function getLogSettings(options){return logSettings||{zone:options.match(/z=.*?;/)[0].replace(/(z=)|(\;)/g,""),sid:options.match(/sid=.*?;/)[0].replace(/(sid=)|(\;)/g,""),ssid:options.match(/ssid=.*?;/)[0].replace(/(ssid=)|(\;)/g,""),medium:options.match(/m=.*?;/)[0].replace(/(m=)|(\;)/g,""),cb:(new Date()).getTime()+Math.floor(Math.random()*99999),adId:options.match(/ad=.*?;/)?options.match(/ad=.*?;/)[0].replace(/(ad=)|(\;)/g,""):options.match(/adid=(.*)?/)[1]}}
function logEvent(action,category){if(logEventURL==""){var adSettings=logSettings||getLogSettings(getClickLink('clickthru'));logEventURL="//adserver.iprom.net/adserver7/iLogger?z="+adSettings.zone+
";t=js;sid="+adSettings.sid+
";ssid="+adSettings.ssid+
";m="+adSettings.medium+
";cb="+adSettings.cb+
";adid="+adSettings.adId+
";iact="+action+
";icat="+category;}
var img=document.createElement("img");img.src=logEventURL;if(logEventURL.match(/adserver\.iprom\.net/)){var adSettings=logSettings||getLogSettings(getClickLink('clickthru')),logEvent9="//core.iprom.net/log/event/?time="+(new Date()).getTime()+Math.floor(Math.random()*99999)+
"&m="+adSettings.medium+
"&sid="+adSettings.sid+
"&ssid="+adSettings.ssid+
"&oadid="+adSettings.adId+
"&z="+adSettings.zone+
"&e="+action+"&v=&c="+category;var i9=document.createElement("img");i9.src=logEvent9;}}
var clickCounter=0;function exitHandler(tag,redirect){if(clickCounter>0)return false;if(typeof tag=='undefined')tag='';if(typeof redirect=='undefined')redirect='';var CT=getClickLink(tag);if(typeof window[tag]!='undefined')CT=window[tag];if(redirect!=''){if(CT.match(/central\.iprom\.net/)){CT+=',';}else{var cparse=CT.match(/rdr=(.*)?/);if(cparse&&cparse.length==2)CT=CT.replace(cparse[1],'');}}
var event={'name':'click'};window.parent.postMessage(event,'*');window.open(CT+redirect);setTimeout(function(){clickCounter=0;},50);clickCounter++;}
function mobilecheck(){var check=false;(function(a,b){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od|ad)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4)))check=true;})(navigator.userAgent||navigator.vendor||window.opera);return check;}
var ipromDEBUG=ipromDEBUG||false;if(typeof ipromTargets!='undefined'&&ipromTargets.length){for(var iat=0;iat<ipromTargets.length;iat++){var CT=getClickLink('clickthru')||clickthru||'';if(CT.match(/central\.iprom\.net/)){CT+=',';}else{var cparse=CT.match(/rdr=(.*)?/);if(cparse===null)continue;if(cparse.length==2)CT=CT.replace(cparse[1],'');}
window['clickthru'+(iat?iat:'')]=CT+ipromTargets[iat];window['clicktag'+(iat+1)]=CT+ipromTargets[iat];window['clickTag'+(iat+1)]=CT+ipromTargets[iat];window['clickTAG'+(iat+1)]=CT+ipromTargets[iat];}}
function waitForSalt(callback){if(typeof creativeSalt=='undefined'||creativeSalt=='')setTimeout(function(){waitForSalt(callback);},50);else callback();}
var $iprom={isMobile:mobilecheck,logEvent:logEvent,click:exitHandler,banner:{resize:function(dim,pos){var opts={status:'geom-update'};if(dim)opts.dimensions=dim;if(pos)opts.position=pos;waitForSalt(function(){opts.salt=creativeSalt;parent.postMessage(opts,'*');});},close:function(){parent.postMessage({event:'close'},'*');},clearParentDimensions:function(l){var opts={status:'clearParentDimensions',level:l};waitForSalt(function(){opts.salt=creativeSalt;parent.postMessage(opts,'*');});}},register:function(e,cb){var opts={register:'event',event:e,callback:cb};waitForSalt(function(){opts.salt=creativeSalt;parent.postMessage(opts,'*');});}};(function(){var fnLazy=function(files,callback){var filesToLoad=0,file,obj,newStylesheetIndex=document.styleSheets.length-1,delay=0;for(index in files)if(files.hasOwnProperty(index)){filesToLoad++;var file=files[index];if(getFileType(file)=='js'){appendScriptAndCallCallback(file);}}
function getFileType(file){file=file.toLowerCase();var jsIndex=file.indexOf('js'),cssIndex=file.indexOf('css');if(jsIndex==-1&&cssIndex==-1)
return false;if(jsIndex>cssIndex)
return 'js';else
return 'css';}
function appendScriptAndCallCallback(url){var oScript=document.createElement('script');oScript.type='text/javascript';oScript.src=url;oScript.onload=decrementAndCallGlobalCallback;document.body.appendChild(oScript);}
function decrementAndCallGlobalCallback(){filesToLoad--;if(filesToLoad==0)
if(typeof callback=='function')callback();}};var VideoHandler={queue:[],dependencies:false,handle:function(v,l){if(v.getAttribute('is')=='gwd-video')return;this.queuePush(v,l);if(this.dependencies)this.queueClear();},loadPlayer:function(){this.dependencies=true;if(this.queue.length)this.queueClear();},queuePush:function(v,l){this.queue.push({video:v,link:l});},queueClear:function(){for(var i=0;i<this.queue.length;i++){var vHolder=document.createElement('div');vHolder.style.position='relative';if(!this.queue[i].video.className.match(/gwd-/)&&(this.queue[i].video.getAttribute('class')==='keep100%')){vHolder.style.width='100%';vHolder.style.height='100%';}else{vHolder.style.width=this.queue[i].video.offsetWidth+'px';vHolder.style.height=this.queue[i].video.offsetHeight+'px';vHolder.style.position=window.getComputedStyle(this.queue[i].video).position;if(vHolder.style.position=="absolute"){vHolder.style.top=this.queue[i].video.offsetTop+'px';if(this.queue[i].video.offsetLeft){vHolder.style.width=this.queue[i].video.offsetWidth+this.queue[i].video.offsetLeft+'px';}}
window.addEventListener('resize',function(){var ratio=vHolder.offsetHeight/vHolder.offsetWidth;vHolder.style.width=vHolder.parentNode.offsetWidth+'px';vHolder.style.height=(vHolder.parentNode.offsetWidth*ratio)+'px';});}
this.queue[i].video.style.maxHeight='initial';if(this.queue[i].video.getAttribute('class'))vHolder.setAttribute('class',this.queue[i].video.getAttribute('class'));if(this.queue[i].video.getAttribute('style')){}
new iPromPlayer(vHolder,{width:this.queue[i].video.offsetWidth,height:this.queue[i].video.offsetHeight,video:this.queue[i].video.getAttribute('sources')?this.queue[i].video.getAttribute('sources'):(this.queue[i].video.children.length?this.queue[i].video.children[0].getAttribute('src'):this.queue[i].video.getAttribute('src')),splash:this.queue[i].video.hasAttribute('poster')?this.queue[i].video.getAttribute('poster'):'',ipromText:{text:''},infoText:false,clickThrough:this.queue[i].link,autoplay:true,mouseoverStart:false,loop:true,style:{background:'transparent'},controls:{play:false,mute:true,progress:false,progressTime:false,fullscreen:!mobilecheck()&&this.queue[i].video.hasAttribute('fullscreen')},sound:{volume:80,onstart:false,mouseover:false},playerEvents:{start:function(){if(this.videoPlayer){this.videoPlayer.style.width='100%';this.videoPlayer.style.height='100%';this.videoPlayer.style.position='absolute';}}}},logSettings);this.queue[i].video.parentNode.appendChild(vHolder);this.queue[i].video.parentNode.removeChild(this.queue[i].video);}}};var scaleInitialized=false;var baseDimensions={};function bindEvent(element,evnt,funct){if(typeof element!='object')return;if(element.attachEvent)return element.attachEvent('on'+evnt,funct);else return element.addEventListener(evnt,funct,false);}
function checkCanvas(){if(document.querySelector('meta[name=widthTrashold]'))resizeImage();}
function hasClass(element,cls){return(' '+element.className+' ').indexOf(' '+cls+' ')>-1;}
function makeMeClickable(el,link){if(el!='undefined'&&typeof el!='undefined'&&!hasClass(el,'ipromCT')){try{el.classList.add('ipromCT');el.style.cursor='pointer';}catch(e){el.class=(el.class?el.class:'')+' ipromCT';}
bindEvent(el,'click',function(evt){if(el.preventDefault)el.preventDefault();var openWindow=true;if(evt.target.className.match(/ipromVideoTag/)&&evt.target!=el)openWindow=false;if(typeof link=='undefined')link=getClickLink(el.id);if(link==''||link=='clickthru'){link=getClickLink();}
if(openWindow){window.open(link);var event={'name':'click','posX':Math.round(evt.pageX),'posY':Math.round(evt.pageY)};window.parent.postMessage(event,'*');}
return false;});}}
function resizeImage(){for(var io=0;io<originals.length;io++){originals[io].el.style.width=(originals[io].width*Math.min(window.innerWidth/tWidth,1))+'px';}}
bindEvent(window,'load',function(){var transparent=QueryString.transparency&&QueryString.transparency=='transparent';var videos=document.querySelectorAll('video:not([class^=gwd]):not([nochange])');if(!videos||!videos.length)videos=[];for(var iv in videos)if(videos.hasOwnProperty(iv)&&!videos[iv].nochange)VideoHandler.handle(videos[iv],getClickLink());if(videos.length)fnLazy(['https://adserver.iprom.net/js/video/videoplayer.js','https://adserver.iprom.net/js/assets/utils.js'],function(){VideoHandler.loadPlayer();});var clickLayers=document.querySelectorAll('[id^=clickthru],[id^=clickTag],.clickthru,[class^=clickthru]');if(!clickLayers||!clickLayers.length)clickLayers=[];for(var ic in clickLayers)if(clickLayers.hasOwnProperty&&clickLayers.hasOwnProperty(ic)){var CT=clickLayers[ic].id&&getClickLink(clickLayers[ic].id.match(/click/)?clickLayers[ic].id:'clickthru');if(clickLayers[ic].tagName=='A'){clickLayers[ic].setAttribute('href',CT);clickLayers[ic].setAttribute('target','_blank');try{clickLayers[ic].classList.add('ipromCT');}catch(e){clickLayers[ic].class=(clickLayers[ic].class?clickLayers[ic].class:'')+' ipromCT';}}else makeMeClickable(clickLayers[ic],CT);}
var nonClickLAyersA=[];try{nonClickLAyersA=document.querySelectorAll('a:not(.ipromCT)');for(var ia in nonClickLAyersA)if(nonClickLAyersA.hasOwnProperty(ia)){if(nonClickLAyersA[ia].href==''||(nonClickLAyersA[ia].href&&nonClickLAyersA[ia].href.length<6)||nonClickLAyersA[ia].text.match(/pravila/))continue;var CT=getClickLink('');if(CT.match(/central\.iprom\.net/)){CT+=',';}else{var cparse=CT.match(/rdr=(.*)?/);if(cparse===null)continue;if(cparse.length==2)CT=CT.replace(cparse[1],'');}
if(typeof nonClickLAyersA[ia].href!='undefined'&&!nonClickLAyersA[ia].href.match('undefined'))
CT=CT+encodeURIComponent(nonClickLAyersA[ia].href);nonClickLAyersA[ia].setAttribute('href',CT);nonClickLAyersA[ia].setAttribute('target','_blank');}}catch(e){}
if(!clickLayers.length&&!nonClickLAyersA.length&&document.body.children[0].tagName=='CANVAS'&&typeof QueryString.clickthru1=='undefined')makeMeClickable(document.body,getClickLink());if(document.querySelector('meta[name=widthThreshold]')){window['tWidth']=Number(document.querySelector('meta[name=widthThreshold]').content);window['originals']=[];var images=document.querySelectorAll('img.resize');for(var i=0;i<images.length;i++)originals.push({el:images[i],width:images[i].offsetWidth,left:images[i].offsetWidth});resizeImage();}
checkCanvas();bindEvent(window,'resize',checkCanvas);});})();