var OA_output = new Array(); 
OA_output['28'] = '';
OA_output['28'] += "<"+"!-- zone: 28, 300x600  -->\n";
OA_output['28'] += "<"+"div class=\"col-xs-12 margin-top text-center zone28 banner17033\"><"+"a href=\'https://revive.adriadigital.si/www/frrr/ck.php?oaparams=2__bannerid=17033__zoneid=28__cb=fd6509fcc9__oadest=https%3A%2F%2Fwww.playboy.si%2Fbranje%2Fnovice%2Fzapeljiva-anara-v-objemu-gora-intervju-z-alesem-stegrom-in-pozdravi-iz-socialisticnega-ekoparadiza%2F\' target=\'_blank\'><"+"img src=\'https://revive.adriadigital.si/www/images/d28594d7210c3429a0f81a6bb7031ff0.png\' width=\'300\' height=\'600\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_fd6509fcc9\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=17033&amp;campaignid=9757&amp;zoneid=28&amp;OACBLOCK=1800&amp;OASCCAP=2&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=fd6509fcc9\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['30'] = '';
OA_output['30'] += "<"+"!-- zone: 30, 728x90  -->\n";
OA_output['30'] += "<"+"!-- iPROM Central - www.centraliprom.com -->\n";
OA_output['30'] += "<"+"script type=\"text/javascript\">\n";
OA_output['30'] += "_iprom_s=\'ez95yjldjkl4to9n\';\n";
OA_output['30'] += "_iprom_d=\'728x90\';\n";
OA_output['30'] += "<"+"/script>\n";
OA_output['30'] += "<"+"script type=\"text/javascript\" src=\"//central.iprom.net/adserver/adserver.js\"><"+"/script>\n";
OA_output['30'] += "<"+"!-- iPROM Central - www.centraliprom.com --><"+"div id=\'beacon_9544dfd53c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=98&amp;campaignid=86&amp;zoneid=30&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=9544dfd53c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['32'] = '';
OA_output['32'] += "<"+"!-- zone: 32, 300x250  -->\n";
OA_output['32'] += "<"+"div class=\"col-xs-12 col-sm-6 col-md-12 margin-top zone32 banner97\"><"+"!-- iPROM Central - www.centraliprom.com -->\n";
OA_output['32'] += "<"+"script type=\"text/javascript\">\n";
OA_output['32'] += "_iprom_s=\'ez95yjldjkl4to9n\';\n";
OA_output['32'] += "_iprom_d=\'300x250\';\n";
OA_output['32'] += "<"+"/script>\n";
OA_output['32'] += "<"+"script type=\"text/javascript\" src=\"//central.iprom.net/adserver/adserver.js\"><"+"/script>\n";
OA_output['32'] += "<"+"!-- iPROM Central - www.centraliprom.com --><"+"div id=\'beacon_147215fa92\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=97&amp;campaignid=86&amp;zoneid=32&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=147215fa92\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['33'] = '';
OA_output['33'] += "<"+"!-- zone: 33, x  -->\n";
OA_output['33'] += "<"+"div id=\'beacon_bc1d128fd9\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=33&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=bc1d128fd9\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['144'] = '';
OA_output['144'] += "<"+"!-- zone: 144, 0x0  -->\n";
OA_output['144'] += "<"+"!-- Oglasno mesto: Lebdeci Pr Lokacija: Adria Media Ljubljana d.o.o. / -->\n";
OA_output['144'] += "<"+"div class=\"iAdserver\" data-iadserver-zone=\"464\"><"+"/div><"+"script type=\"text/javascript\">iprom_ZONES.push(464);<"+"/script><"+"div id=\'beacon_7cddbbb2bf\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=17174&amp;campaignid=6562&amp;zoneid=144&amp;OAZBLOCK=3600&amp;OASZCAP=2&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=7cddbbb2bf\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['156'] = '';
OA_output['156'] += "<"+"!-- zone: 156, x  -->\n";
OA_output['156'] += "<"+"div id=\'beacon_910d656f98\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=156&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=910d656f98\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['208'] = '';
OA_output['208'] += "<"+"!-- zone: 208, 960x250  -->\n";
OA_output['208'] += "<"+"div id=\"am_pd_banner\" class=\"text-center margin-top\" style=\"width: auto !important; position: inherit; z-index: 100;max-width: 970px;margin-left: auto; margin-right: auto;overflow: hidden; background-color: white;\"><"+"script>console.log(\"iprombb\")<"+"/script><"+"div id=\"ibb6275\">\n";
OA_output['208'] += "<"+"!-- iPROM - 440 Billboard - AML -->\n";
OA_output['208'] += "<"+"div class=\"iAdserver\" data-iadserver-zone=\"440\"><"+"/div><"+"script type=\"text/javascript\">iprom_ZONES.push(440);<"+"/script>\n";
OA_output['208'] += "<"+"script>\n";
OA_output['208'] += "function iprom_bb_fallback(sid){\n";
OA_output['208'] += "var fallback = \"<"+"div style=\'text-align: center;\'><"+"iframe style=\'margin-bottom: 5px;\' id=\'a27d8c32\' name=\'a27d8c32\' src=\'https://revive.adriadigital.si/www/frrr/afr.php?zoneid=114&amp;cb=1554796317.5583&amp;noas={noas}\' frameborder=\'0\' scrolling=\'no\' width=\'728\' height=\'90\'><"+"a href=\'https://revive.adriadigital.si/www/frrr/ck.php?oaparams=2__bannerid=6275__zoneid=208__cb=5dc9bfd9b7__oadest=https%3A%2F%2Frevive.adriadigital.si%2Fwww%2Ffrrr%2Fck.php%3Fn%3Dac178391%26cb%3D1554796317.5583\' target=\'_blank\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/avw.php?zoneid=114&amp;cb=1554796317.5583&amp;n=ac178391\' border=\'0\' alt=\'\' /><"+"/a><"+"/iframe><"+"/div>\";\n";
OA_output['208'] += "document.getElementById(\'ibb6275\').innerHTML = fallback;\n";
OA_output['208'] += "}\n";
OA_output['208'] += "<"+"/script>\n";
OA_output['208'] += "<"+"/div><"+"div id=\'beacon_5dc9bfd9b7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=6275&amp;campaignid=4535&amp;zoneid=208&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=5dc9bfd9b7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['208'] += "<"+"script type=\"text/javascript\" src=\"https://revive.adriadigital.si/www/js/pushdown.js\"><"+"/script>\n";
OA_output['245'] = '';
OA_output['245'] += "<"+"!-- zone: 245, x  -->\n";
OA_output['245'] += "<"+"div id=\'beacon_13eba1f767\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=245&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=13eba1f767\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['311'] = '';
OA_output['311'] += "<"+"!-- zone: 311, 640x480  -->\n";
OA_output['311'] += "<"+"div id=\"adform-outstream\" style=\"height:0;overflow:hidden;\">\n";
OA_output['311'] += "<"+"script language=\"javascript\" src=\"//s1.adform.net/banners/scripts/video/outstream/inview.js\"\n";
OA_output['311'] += "data-pmp-id=\"451593\"\n";
OA_output['311'] += "data-skip-button-label=\"preskoči\"\n";
OA_output['311'] += "data-close-oncomplete=\"false\">\n";
OA_output['311'] += "<"+"/script>\n";
OA_output['311'] += "<"+"/div><"+"div id=\'beacon_35325fbbbc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=12853&amp;campaignid=7908&amp;zoneid=311&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=35325fbbbc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['363'] = '';
OA_output['363'] += "<"+"!-- zone: 363, 300x250  -->\n";
OA_output['363'] += "<"+"div class=\"col-xs-12 col-sm-6 col-md-12 margin-top zone363 banner14353\"><"+"a href=\'https://revive.adriadigital.si/www/frrr/ck.php?oaparams=2__bannerid=14353__zoneid=363__cb=456a94e73b__oadest=https%3A%2F%2Fwww.moja-diagnoza.si%2F\' target=\'_blank\'><"+"img src=\'https://revive.adriadigital.si/www/images/5b3aaed8b7f2cb63434f751fc1034ac8.jpg\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_456a94e73b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=14353&amp;campaignid=8674&amp;zoneid=363&amp;OACBLOCK=28800&amp;OASCCAP=1&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=456a94e73b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['369'] = '';
OA_output['369'] += "<"+"!-- zone: 369, 640x480  -->\n";
OA_output['369'] += "<"+"script>\n";
OA_output['369'] += "var ox_vast = ox_vast || [];\n";
OA_output['369'] += "ox_vast.push({\n";
OA_output['369'] += "\'vasturl\': \"https://sigde.adocean.pl/_{TIMESTAMP}/ad.xml?id=1_QALWtvNygFeiHCzwcv80VucMB9oAN4XD56Vjcpz1v.w7/nc=0/gdpr=0/gdpr_consent=/redir=\",\n";
OA_output['369'] += "\'bannerid\': \'17429\'\n";
OA_output['369'] += "});\n";
OA_output['369'] += "<"+"/script>\n";
OA_output['369'] += "<"+"script src=\"https://revive.adriadigital.si/www/vOglas/static/ba2vast/vo.js\"><"+"/script>\n";
OA_output['369'] += "<"+"div id=\"voba2vast17429\" data-clickurl=\"https://revive.adriadigital.si/www/frrr/ck.php?oaparams=2__bannerid=17429__zoneid=369__cb=19b09f2fa0__oadest=\" data-statsurl=\"https://revive.adriadigital.si/www/frrr/fc.php?script=videoAds:vastEvent&bannerid=17429&zoneid=369&event=\"><"+"/div><"+"div id=\'beacon_19b09f2fa0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://revive.adriadigital.si/www/frrr/lg.php?bannerid=17429&amp;campaignid=9893&amp;zoneid=369&amp;loc=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;referer=https%3A%2F%2Fwww.avto-magazin.si%2Fnovice%2Fodkrivamo%2Frazkrivamo-volkswagen-golf-8-prihaja-naslednje-leto-namesto-letos%2F&amp;cb=19b09f2fa0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
